---
- name: Create milvus-etcd, minio, pulsar #Milvus基本的依赖组件，部署在同一台Host上便于控制IP地址
  hosts: dependencies
  become: yes
  become_user: root
  tags: docker
  roles:
    # - deploy-etcd
    - deploy-minio
    - deploy-pulsar

- name: Create milvus nodes #将Milvus的3个node角色部署到同一个Host，可以搭配读写优化的磁盘
  hosts: nodes
  become: yes
  become_user: root
  tags: docker
  roles:
    - deploy-datanode
    - deploy-indexnode
    - deploy-querynode

- name: Create milvus coords #将4个Milvus的Coordinator，和一个Proxy部署在同一个Host，可以做相应的优化配置，如果有其它方面的考虑，可以将Proxy分离出来
  hosts: coords
  become: yes
  become_user: root
  tags: docker
  roles:
    - deploy-rootcoord
    - deploy-indexcoord
    - deploy-datacoord
    - deploy-querycoord
    - deploy-proxy




  



